services:
  db:
    image: postgres:16-alpine
    container_name: n8n_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_application
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST}
      - DB_POSTGRESDB_PORT=${POSTGRES_PORT}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=${WEBHOOK_URL}
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2-alpine
    container_name: n8n_caddy_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      N8N_HOST: ${N8N_HOST}
      SSL_EMAIL: ${SSL_EMAIL}
      CADDYFILE_CONTENT: |
        ${N8N_HOST} {
            reverse_proxy n8n:5678 {
                flush_interval -1
            }
            encode gzip zstd
            log {
                output file /var/log/caddy/access.log
            }
        }
    entrypoint:
      - sh
      - -c
      - |
        echo "$$CADDYFILE_CONTENT" > /etc/caddy/Caddyfile
        exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - n8n


volumes:
  postgres_storage:
    name: n8n_postgres_storage
  n8n_storage:
    name: n8n_storage_data
  caddy_data:
    name: n8n_caddy_data
  caddy_config:
    name: n8n_caddy_config
  caddy_logs:
    name: n8n_caddy_logs
